### ISSUE TITLE
Date filter requires at least one option?

### ISSUE THREAD

**Issue by vchokshi** [logstash-plugins/logstash-filter-date#25] opened 2015-06-06 17:09 UTC
Hi - I tried to use the date filter by itself 

filter { date {} }

and I got this error: 

{:timestamp=>"2015-06-06T10:02:25.825000-0700", :message=>"Error: Cannot register filter date plugin. The error reported is: \n  The match setting should contains first a field name and at least one date format, current value is []"}

The documentation indicates no required option. 

All I am trying to do is append a timestamp to the [timestamp] field so I can compare start vs. finish of all my filters. Per my understanding the input filter adds timestamp and my goal is to add another timestamp just before entering output.

**Comment by vchokshi** [comment] 2015-06-06 17:25
I tried this workaround but I can't seem to get timestamp_end to populate. 

date {
    match => ["timestamp", "MMM dd YYY HH:mm:ss",
          "MMM  d YYY HH:mm:ss", "ISO8601" ]
    target => "timestamp_end"
  }

the match should work give the timestamp = "Jun  6 10:22:25"

Am I doing something wrong?

**Comment by vchokshi** [comment] 2015-06-06 17:37
Here's a workaround.
 date {
    match => ["timestamp", "MMM dd YYY HH:mm:ss",
          "MMM  d HH:mm:ss", "ISO8601" ]
    target => "timestamp_end"
  }

Any chance we can add ms or even ns to this field to see processing time of ls from start to finish?

Thank you!

**Comment by purbon** [comment] 2015-11-02 16:45
@vchokshi first question, you require what you just discover, the pattern to do the conversion. This plugin  is about normalizing timestamp, not generating them. Please see https://www.elastic.co/guide/en/logstash/current/plugins-filters-date.html for more details.

re: second question: this is being workout at #8 

Closing this as duplicate of #29 and because of the first question being already answered in this comment. Feel free to reopen if new issues are arised.

**Closed by purbon** 2015-11-02 16:45 UTC
